name: Build and publish

on:
  push:
  schedule:
    - cron: '0 9 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Publish

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/build-agent:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/build-agent:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/build-agent:buildcache,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
